author: blueMix
description: Ù…Ø¯ÙˆÙ†Ø© Ø¹Ø¨Ø¯ Ø§Ù„Ù…Ø¤Ù…Ù†
keywords: hexo-theme, rexo, rtl, multilingual

menu:
#  ğŸ : /
#  ğŸ·: /tags/
#  ğŸ“—: /archives/
#  ğŸ’»: /projects/
#  ğŸ: /photography/
 ğŸ‘¨ğŸ»â€ğŸ’»: /about/

# highlight
highlight:
  tomorrow


# Comment
comment:
    disqus: disqus_FoW5JlagXA


about: 
  avatar: https://avatars3.githubusercontent.com/u/3332274?v=4&s=460
  description: Peace  â˜®ï¸  Ø§Ù„Ø³Ù„Ø§Ù… 

# Customize
customize:
    sidebar: right # sidebar position, options: left, right or leave it empty

deploy:
  type: git
  repo: <repository url>
  branch: [branch]
  message: [message]

# Miscellaneous
miscellaneous:
    links:
      - link:
        - Archive | Ø§Ù„Ø£Ø±Ø´ÙŠÙ
        - /archives/
        - ğŸ“—
      - link: 
        - Quotes | Ø­ÙƒÙ…
        - /quotes/
        - ğŸ“
      - link: 
        - Songs & Music | Ù…ÙˆØ³ÙŠÙ‚Ù‰ Ùˆ Ø£ØºØ§Ù†ÙŠ
        - /music
        - ğŸµ
      - link: 
        - Inspired by | Ø£Ø´Ø®Ø§Øµ Ø£Ø­Ø¨Ù‡Ù…
        - /inspired
        - ğŸ’–


