author: blueMix
description: Ù…Ø¯ÙˆÙ†Ø© Ø¹Ø¨Ø¯ Ø§Ù„Ù…Ø¤Ù…Ù†
keyword: hexo-theme, rexo

menu:
#  ğŸ : /
#  ğŸ·: /tags/
#  ğŸ“—: /archives/
#  ğŸ’»: /projects/
#  ğŸ: /photography/
 ğŸ‘¨ğŸ»â€ğŸ’»: /about/

# highlight
highlight:
  tomorrow


# Comment
comment:
    disqus: disqus_FoW5JlagXA


about: 
  avatar: https://avatars3.githubusercontent.com/u/3332274?v=4&s=460
  description: Peace  â˜®ï¸  Ø§Ù„Ø³Ù„Ø§Ù… 

# Customize
customize:
    sidebar: right # sidebar position, options: left, right or leave it empty

# Widgets
widgets:
    # - recent_posts
    # - category
    # - tag
    # - tagcloud
    # - archive
    - links

# Miscellaneous
miscellaneous:
    links:
      - link:
        - Archive | Ø§Ù„Ø£Ø±Ø´ÙŠÙ
        - /archives/
        - ğŸ“—
      - link: 
        - Quotes | Ø­ÙƒÙ…
        - http://fb.com/bluemix
        - ğŸ“
      - link: 
        - Songs & Music | Ù…ÙˆØ³ÙŠÙ‚Ù‰ Ùˆ Ø£ØºØ§Ù†ÙŠ
        - http://twitter.com/bluemix2
        - ğŸµ
      - link: 
        - Inspired by | Ø£Ø´Ø®Ø§Øµ Ø£Ø­Ø¨Ù‡Ù…
        - http://instagram.com/bluemix
        - ğŸ’–


